### ISSUE TITLE
Rewrite resnet implementations as block + model?

### ISSUE THREAD

**Issue by dustinvtran** [google/edward2#126]
Resnets in CIFAR/ImageNet currently write a generic conv, bn, and relu layer, and the model function stacks these.

I like Pytorch's implementations which more closely resemble how we think of resnets: define a residual block function (which itself can vary), and then define a model which stacks residual blocks. These seems conceptually nicer but may require more boilerplate as the conv layer takes quite a few arguments.

**Comment by dusenberrymw** [comment]
+1. I have a version written already that uses the residual block form.

**Comment by dustinvtran** [comment]
Fixed in WRN-28-10 implementations (https://github.com/google/edward2/pull/133).
