### ISSUE TITLE
module 'edward2' has no attribute 'layers

### ISSUE THREAD

**Issue by neginjv** [google/edward2#237]
@dustinvtran Hi, I am using your library for my research. I want to build lstm cell So I used your code :lstm=ed.layers.LSTMCellReparameterization(512). But I got an error: module 'edward2' has no attribute 'layers
Could someone help me please?

**Comment by neginjv** [comment]
@dustinvtran Could you help me for this code what libraries should I import?
lstm=ed.layers.LSTMCellReparameterization(512)

**Comment by dustinvtran** [comment]
Have you installed TF and TFP? Otherwise the imports into the namespace won't happen: https://github.com/google/edward2/blob/master/edward2/tensorflow/__init__.py#L26.

**Comment by neginjv** [comment]
@dustinvtran Yes. I have installed them. I used this code: lstm=ed.tensorflow.layers.LSTMCellReparameterization(512)
Is it true?
If you shares a guide  for bayesian lstm code it would be really perfect. I think your code in your paper for bayesian layers is  different   from the one in your poster and in your github there isnt any explanation about bayesian lstm.

**Comment by neginjv** [comment]
@dustinvtran Hi, I check your github and can't find a source code for bayesian lstm. Your code in your paper and your poster are totally different. Could you help me?

**Comment by neginjv** [comment]
@dustinvtran  Thanks for your help.

**Comment by dustinvtran** [comment]
Great! Marking closed assuming this is resolved.
