### ISSUE TITLE
Problem Importing Layer Modules

### ISSUE THREAD

**Issue by jejjohnson** [google/edward2#30]
Hello,

I was eager to try out some of the [Bayesian layers](https://arxiv.org/pdf/1812.03973) that you had implemented. I saw that they were in the [tensor2tensor](https://github.com/tensorflow/tensor2tensor) package but then they seemed to have been [removed](https://github.com/tensorflow/tensor2tensor/commit/23f03a2ee5fda24234e8cc0573e3f727435a9428) placed in the edward2 package in the [layers part](https://github.com/google/edward2/issues/13). but I can't seem to find any of the modules (e.g. GaussianProcess, SparseGaussianProcess) or perhaps I don't understand how it works with importing them. I thought maybe perhaps the names were different but I can't seem to wrap my head around where to find the bayesian layer modules. 

I cannot even find the files within the actual distribution located in `/usr/local/lib/python3.6/dist-packages/edward2/__init__.py` so I'm not sure if I am doing something wrong or not.

---
**Installations**

I did the following installation procedure with and without the tf-nightly

```python
pip install edward2[tf-nightly]
```

I also tried to directly install it via the github repo:

```python
pip install git+https://github.com/google/edward2
```

---
**Helpful Info**

* Google Colab Notebook
* Python 3.6
* TensorFlow - 2.0.0-rc1
* Edward - 0.0.1

Thanks,
Emmanuel

**Comment by dusenberrymw** [comment]
Hi Emmanuel,

Thanks for reaching out!  The Bayesian Layers are now located under the [`ed.layers` namespace](https://github.com/google/edward2/blob/master/edward2/tensorflow/layers/__init__.py#L55-L86), and the files are physically located in the [`edward2/tensorflow/layers`](https://github.com/google/edward2/blob/master/edward2/tensorflow/layers/) subdirectory.

For example, the following works with the current master branch:

```py3
import tensorflow.compat.v2 as tf
import edward2 as ed
tf.enable_v2_behavior()

dense_layer = ed.layers.DenseReparameterization(10)

x = tf.random.normal([3,4])
y = dense_layer(x)
```

**Comment by jejjohnson** [comment]
Thank you for the help! I ran it again on Colab and on my own system and I had success! I imagine it may have had something to do with the recent update or I had an outdated version of some sort. 

In any case, all is good and I'm eager to use it. 

Thank you! 

Closing the issue.

**Comment by jejjohnson** [comment]
Hello,

I'd like to quickly reopen the issue. I was wondering what was the version number of tensorflow and tensorflow_probability when you ran the above example code above?

I reopened the colab notebook and had to reinstall tensorflow, tensorflow_probability and edward2. And now it doesn't work anymore so I'm wondering what is the problem. I also tried it on my machine with a fresh install and got the same error. My current version numbers:

```bash
python=3.6
tensorflow=2.0
tensorflow_probability=0.8.0
edward=0.0.1
```
After running the following code:

```python
!pip install --upgrade --force-reinstall tensorflow-gpu
!pip install --upgrade --force-reinstall tensorflow-probability
!pip install --upgrade --force-reinstall edward2
```

I get the following error message:

```python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-10-247126858d79> in <module>
----> 1 import edward2 as ed

~/.conda/envs/dl_py36/lib/python3.6/site-packages/edward2/__init__.py in <module>
     30 
     31 from tensorflow_probability import distributions
---> 32 from edward2 import generated_random_variables
     33 from edward2.generated_random_variables import *  # pylint: disable=wildcard-import
     34 from edward2.generated_random_variables import make_random_variable

~/.conda/envs/dl_py36/lib/python3.6/site-packages/edward2/generated_random_variables.py in <module>
     24 
     25 from tensorflow_probability import distributions
---> 26 from tensorflow_probability.python.util import docstring as docstring_util
     27 from edward2.random_variable import RandomVariable
     28 from edward2.trace import traceable

ImportError: cannot import name 'docstring'
```

Thank you again.

**Comment by dustinvtran** [comment]
Thanks for looking into this. We haven't released a new PyPI package yet. You should do
```sh
pip install -e "git+https://github.com/google/edward2.git#egg=edward2"
```
I'm not sure when we'll release a new package version. This is a good reminder in any case to point the installation details to use the above command!
