### ISSUE TITLE
AttributeError: module 'edward2' has no attribute 'dirichlet'

### ISSUE THREAD

**Issue by pprabb** [google/edward2#351]
I am very new to probabilistic programming. I have been studying about this for a month and trying to implement an lda model using edward2 with this code

`import tensorflow as tf
import edward2 as ed

D = 4
N = [11502,213,1523,1351]
K = 10
V = 100000

theta = ed.dirichlet(tf.zeros([D,K]) + 0.1
phi = ed.dirichlet(tf.zeros([K,V]) + 0.05
z = [[0] * N] * D
w = [[0] *N] * D
for d in range[D]:
    for n in range(N[d]):
        z[d][n] = ed.Categorical(theta[d, :])
        w[d][n] = ed.Categorical(phi[z[d][n], :])`

which is from figure 11 here [http://edwardlib.org/iclr2017?fbclid=IwAR0u2jH9VNhhMUad5LHbJt1aAyiz6kJ04pbNDmUeQsUDBW5iXJ11UuQ9XGI](url)
and I got this error

> 
Traceback (most recent call last):
  File "ed2lda.py", line 9, in <module>
    theta = ed.dirichlet(tf.zeros([D,K]) + 0.1)
AttributeError: module 'edward2' has no attribute 'dirichlet'

I think this might be some import error that is not about is my code correct ( because I am not that sure is it). However, it would be really helpful if anyone can show me the example of implementing lda model using edward2

**Comment by ksachdeva** [comment]
Try:

ed.Dirichlet

**Comment by dustinvtran** [comment]
Marking as fixed. :-)
