### ISSUE TITLE
Edward.PointMass?

### ISSUE THREAD

**Issue by NeilGirdhar** [google/edward2#363]
What is the edward2 version of `edward.PointMass`?  It appears that the only mention of it is in the upgrading instruction file, but no update instructions are provided.  I'm trying to port someone else's outdated code.

**Comment by dustinvtran** [comment]
Have you tried ed.Deterministic?

See https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/Deterministic.

**Comment by NeilGirdhar** [comment]
Okay, thanks.
