### ISSUE TITLE
AttributeError: module 'edward2' has no attribute 'KLqp'

### ISSUE THREAD

**Issue by nbro** [google/edward2#38]
I am trying to run this example https://github.com/blei-lab/edward/blob/master/examples/bayesian_nn.py, but with edward 2 and TensorFlow 2 (which is now stable). After having first used the script `tf_upgrade_v2` on this file and fixed other problems mentioned in this issue https://github.com/google/edward2/issues/37, I get another error 

> Traceback (most recent call last):
  File "/Users/nbro/Desktop/edward_tests/edward_test2.py", line 102, in <module>
    app.run(main)
  File "/Users/nbro/Desktop/edward_tests/venv/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/Users/nbro/Desktop/edward_tests/venv/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/Users/nbro/Desktop/edward_tests/edward_test2.py", line 95, in main
    inference = ed.KLqp({W_0: qW_0, b_0: qb_0, W_1: qW_1, b_1: qb_1, W_2: qW_2, b_2: qb_2},
AttributeError: module 'edward2' has no attribute 'KLqp'

I noticed that https://github.com/google/edward2/blob/master/Upgrading_From_Edward_To_Edward2.md shows an example of how to perform inference with edward 2. This example is extremely verbose, compared to edward 1's example, which just calls `KLqp`. Is there an easy (non-verbose) way of performing inference with edward 2 (with TensorFlow 2)?

This issue may be related to https://github.com/blei-lab/edward/issues/640.

**Comment by dustinvtran** [comment]
Marking closed from discussion in #37.
