### ISSUE TITLE
AttributeError: module 'edward2' has no attribute 'layers'

### ISSUE THREAD

**Issue by QiyaoWei** [google/edward2#502]
I am aware of #237, but unfortunately there does not seem to be a well-defined solution in that issue. In my case, I am having this issue when I run the following code (from uncertainty_baselines)
```
    Conv2DBatchEnsemble = functools.partial(  # pylint: disable=invalid-name
        ed.layers.Conv2DBatchEnsemble,
        kernel_size=3,
        padding='same',
        use_bias=False,
        kernel_initializer='he_normal')
```
I believe I have downloaded tf2 and tf-probability. I have also tried both "pip install edward2" and installing from source. Could you kindly point out what else I might be missing? Thanks a lot!

**Comment by liuyx599** [comment]
Hello, I have encountered the same problem as you. May I ask how you ultimately resolved it

**Comment by xchen99sdr** [comment]
same issue persists

**Comment by QiyaoWei** [comment]
I believe I resolved this issue by adjusting the package versions, so I would presume that is still the problem.
