### ISSUE TITLE
Installation problem WSL

### ISSUE THREAD

**Issue by rlsandovalp** [google/edward2#566]
Hi, I'm facing some problems when installing eduard2. When I run the pip install lines (TensorFlow probability and edward2) it seems to work, however, when I try to call the library it raises an error that I don't understand. If relevant, I'm using WSL and an environment created with miniconda.

![image](https://github.com/google/edward2/assets/51087450/4931c2e7-19d7-4fed-ace6-880144c7d9e9)

**Comment by Krasner** [comment]
I am seeing this issue on linux too without conda. If I install from github (or install with `pip install -e .`) I get a backend error:
`ImportError: No backend is available for Edward2. Please install dependencies for JAX, NumPy, or TensorFlow.`

**Comment by Krasner** [comment]
It looks like a scipy problem. Reinstall with version 1.7.3
`pip install scipy==1.7.3` should work
